package helpers;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class ClassFinderHelper {
    public static Set<String> currentClassNames = new HashSet<>(Arrays.asList(
            "helpers.ClassFinderHelper",
            "helpers.DataAccessCreatorTestStubs",
            "helpers.DatabaseWrapperStubs$1",
            "helpers.DatabaseWrapperStubs",
            "helpers.EntityAccessCreatorStubs",
            "helpers.JSONMappingStubs",
            "helpers.RolesForUsersCreatorStubs",
            "initializationModule.abstractObjectCreators.DataAccessCreatorTest",
            "initializationModule.abstractObjectCreators.EntityAccessCreatorTest",
            "initializationModule.abstractObjectCreators.RolesForUsersCreatorTest",
            "initializationModule.abstractObjectCreators.RolesListCreatorTest$JSONReadingTest",
            "initializationModule.abstractObjectCreators.RolesListCreatorTest",
            "initializationModule.integrationTests.InitializationModuleIntegrationTests",
            "initializationModule.mappingFactories.DataAccessJSONMappingTest$JSONReadingTest",
            "initializationModule.mappingFactories.DataAccessJSONMappingTest",
            "initializationModule.mappingFactories.EntityAccessJSONMappingTest$JSONReadingTest",
            "initializationModule.mappingFactories.EntityAccessJSONMappingTest",
            "initializationModule.mappingFactories.RolesForUsersJSONMappingTest$JSONReadingTest",
            "initializationModule.mappingFactories.RolesForUsersJSONMappingTest",
            "initializationModule.mappingFactories.RolesListJSONMappingTest$JSONReadingTest",
            "initializationModule.mappingFactories.RolesListJSONMappingTest",
            "initializationModule.utils.ClassFinderTest",
            "org.safety.library.annotations.ProtectedData",
            "org.safety.library.annotations.Users",
            "org.safety.library.hibernate.SessionProvider",
            "org.safety.library.initializationModule.abstractMappingObjects.DataAccess",
            "org.safety.library.initializationModule.abstractMappingObjects.EntityAccess",
            "org.safety.library.initializationModule.abstractMappingObjects.RolesForUsers",
            "org.safety.library.initializationModule.abstractMappingObjects.RolesList",
            "org.safety.library.initializationModule.abstractMappingUsers.DataAccessUser",
            "org.safety.library.initializationModule.abstractMappingUsers.EntityAccessUser",
            "org.safety.library.initializationModule.abstractMappingUsers.RolesForUsersUser",
            "org.safety.library.initializationModule.abstractMappingUsers.RolesListUser",
            "org.safety.library.initializationModule.abstractObjectCreators.DataAccessCreator",
            "org.safety.library.initializationModule.abstractObjectCreators.EntityAccessCreator",
            "org.safety.library.initializationModule.abstractObjectCreators.RolesForUsersCreator",
            "org.safety.library.initializationModule.abstractObjectCreators.RolesListCreator",
            "org.safety.library.initializationModule.Exceptions.ClassWithAnnotationDidntFound",
            "org.safety.library.initializationModule.Exceptions.RoleForUserNotFoundException",
            "org.safety.library.initializationModule.Initializer",
            "org.safety.library.initializationModule.JSONMapping",
            "org.safety.library.initializationModule.JSONMappingFactory",
            "org.safety.library.initializationModule.JSONMappingUser",
            "org.safety.library.initializationModule.mappingFactories.DataAccessJSONMapping",
            "org.safety.library.initializationModule.mappingFactories.EntityAccessJSONMapping",
            "org.safety.library.initializationModule.mappingFactories.RolesForUsersJSONMapping",
            "org.safety.library.initializationModule.mappingFactories.RolesListJSONMapping",
            "org.safety.library.initializationModule.testEntities.SomeProtectedClass1",
            "org.safety.library.initializationModule.testEntities.SomeProtectedClass2",
            "org.safety.library.initializationModule.testEntities.SomeUnprotectedClass1",
            "org.safety.library.initializationModule.testEntities.TestUsers",
            "org.safety.library.initializationModule.utils.Authenticator$AuthenticatorHelper",
            "org.safety.library.initializationModule.utils.Authenticator",
            "org.safety.library.initializationModule.utils.ClassFinder",
            "org.safety.library.initializationModule.utils.DatabaseWrappers",
            "org.safety.library.initializationModule.utils.Permission",
            "org.safety.library.initializationModule.utils.PriviledgesReader",
            "org.safety.library.Main",
            "org.safety.library.models.AccessListRow",
            "org.safety.library.models.AddPrivilege",
            "org.safety.library.models.HibernateSelect",
            "org.safety.library.models.Role",
            "org.safety.library.models.TestModel",
            "org.safety.library.models.UsersRole",
            "org.safety.library.RolesPrivilegesMap.RolesPrivilegesMap",
            "org.safety.library.SQLModule.Builder",
            "org.safety.library.SQLModule.DerbyQueryBuilder",
            "org.safety.library.SQLModule.QueryInterceptor",
            "org.safety.library.SQLModule.QueryMaster",
            "org.safety.library.updateModule.UpdateACL"
            ));
}
